fix compile error after update to Clang 11.0.4
Fixes errors like:
../../../../../../kernel/oneplus/sm8150/coretech/memplus/core/memplus_core.c:105:30: error: this old-style function definition is not preceded by a prototype [-Werror,-Wstrict-prototypes]
bool ctech_current_is_swapind() {

Change-Id: I6c523dece557763ae76ae0b2c83a41c6685e34e5